version: '3'

services:
  cli-agent:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - ./plugins:/app/plugins
      - ./templates:/app/templates
    environment:
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_API_HOST=https://llm.chutes.ai/v1
      - LLM_MODEL_NAME=chutesai/Llama-4-Scout-17B-16E-Instruct
      - TERM=xterm-256color
      - COLORTERM=truecolor
    stdin_open: true
    tty: true
    command: --working-dir /data --state-file /data/agent_state.json --plugin-dir /app/plugins --templates-dir /app/templates
